In [1]:
import sys
import numpy as np
l=range(1000)
print(sys.getsizeof(5)*len(l))
array=np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [3]:
import time
SIZE=1000000
l1=range(SIZE)
l2=range(SIZE)
a1=np.array(SIZE)
a2=np.array(SIZE)
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("python list time:",(time.time()-start)*1000)
start=time.time()
result=a1+a2
print("numpy time:",(time.time()-start)*1000)

python list time: 304.64696884155273
numpy time: 49.93867874145508


In [5]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [7]:
l=[1,2,3,4,5]
b=[a+1 for a in l]
b

[2, 3, 4, 5, 6]

In [8]:
import numpy as np
l=np.array(l)
b=l+1
b

array([2, 3, 4, 5, 6])

In [10]:
a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])
a.dot(b)

array([[25, 28],
       [57, 64]])

In [11]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [12]:
a.itemsize

8

In [13]:
a.dtype

dtype('int64')

In [14]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.size

6

In [16]:
a.shape

(3, 2)

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
a.shape

(3, 2)

In [20]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.arange(1,5,2)

array([1, 3])

In [23]:
np.linspace(1,5 ,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a.min()

np.int64(1)

In [26]:
a.max()

np.int64(6)

In [27]:
a.sum(axis=0)

array([ 9, 12])

In [28]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [29]:
np.std(a)

np.float64(1.707825127659933)

In [30]:
import numpy as np
a=np.array([1,2,3,4])
a[0:2]

array([1, 2])

In [31]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a[0:2,2,0:2]

array([[ 7,  8],
       [16, 17]])

In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [34]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [35]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [37]:
result=np.hsplit(a,5)
result[0:6]

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [38]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [39]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [42]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [43]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [44]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [45]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [47]:
np.mod(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
np.power(a,b)

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [49]:
np.reciprocal(a)

array([[1, 0, 0],
       [0, 0, 0]])

In [50]:
c=np.array([1.,2.,3.,4.,5.])
c

array([1., 2., 3., 4., 5.])

In [51]:
d=np.reciprocal(c)
d

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [52]:
a=np.arange(12).reshape(3,4)
print(a)
for x in np.nditer(a,order='C'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [53]:
a=np.arange(12).reshape(3,4)
print(a)
for x in np.nditer(a,order='F'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11


In [54]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [55]:
a=np.arange(12).reshape(3,4)
print(a)
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=2*x
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [57]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a[1,0:2,1]

array([ 8, 11])

In [60]:
import numpy as np
items=np.array([0,1,2,3,4,5])
new_items=items.copy()
print(items)
print(id(items))
print(new_items)
print(id(new_items))

[0 1 2 3 4 5]
2281441282640
[0 1 2 3 4 5]
2281399934896


In [61]:
import numpy as np
items=np.array([0,1,2,3,4,5,6,7])
new_items=items.copy()
print("items : ",items)
print(id(items))
print()
print()
print("new_items : ",new_items)
print(id(new_items))
print()
print("after changes in new_items:\n")
new_items += 10
print("items : ",items)
print()
print("new_items:",new_items)

items :  [0 1 2 3 4 5 6 7]
2281441293680


new_items :  [0 1 2 3 4 5 6 7]
2281441282640

after changes in new_items:

items :  [0 1 2 3 4 5 6 7]

new_items: [10 11 12 13 14 15 16 17]


In [64]:
import numpy as np
items = np.array([0,1,2,3,4,5,6,7])
new_items=items.copy()
print("items:",items)
print()
print("new_items:",new_items)
print()
print("After changes in items:\n")
items +=10
print("items:",items)
print()
print("new_items:",new_items)

items: [0 1 2 3 4 5 6 7]

new_items: [0 1 2 3 4 5 6 7]

After changes in items:

items: [10 11 12 13 14 15 16 17]

new_items: [0 1 2 3 4 5 6 7]


In [66]:
import numpy as np
items = np.array([0,1,2,3,4,5])
new_items=items.view()
print(items)
print(id(items))
print()
print(new_items)
print(id(new_items))

[0 1 2 3 4 5]
2281441292432

[0 1 2 3 4 5]
2281441292624


In [67]:
import numpy as np
items=np.array([0,1,2,3,4,5,6,7])
new_items=items.view()
print("items:",items)
print(id(items))
print()
print("new_items:",new_items)
print(id(new_items))
print()
print("After changes in new_items:\n")
new_items +=10
print("items:",items)
print()
print("new_items:",new_items)

items: [0 1 2 3 4 5 6 7]
2281441294544

new_items: [0 1 2 3 4 5 6 7]
2281441651728

After changes in new_items:

items: [10 11 12 13 14 15 16 17]

new_items: [10 11 12 13 14 15 16 17]


In [68]:
l=[1,2,3]
l1=l.view()
print(id(l))
print(id(l1))

AttributeError: 'list' object has no attribute 'view'

In [69]:
import numpy as np
items=np.array([0,1,2,3,4,5])
new_items=items
print(items)
print(id(items))
print()
print(new_items)
print(id(new_items))

[0 1 2 3 4 5]
2281441653456

[0 1 2 3 4 5]
2281441653456


In [70]:
import numpy as np
items=np.arange(9)
print("items:",items)
new_items=items.reshape(3,3)
print("new_items:\n",new_items)
print()
new_items=new_items.ravel()
print(new_items)
print()
print(new_items.base)

items: [0 1 2 3 4 5 6 7 8]
new_items:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 3 4 5 6 7 8]

[0 1 2 3 4 5 6 7 8]


In [71]:
import numpy as np
items=np.arange(9).reshape(3,3)
print("items:",items)
new_items=items.flatten()
print()
print("new_items:",new_items)
print()
print(new_items.base)

items: [[0 1 2]
 [3 4 5]
 [6 7 8]]

new_items: [0 1 2 3 4 5 6 7 8]

None


In [72]:
import numpy as np
items=np.arange(10)
print("items:",items)
print()
items_view=items.view()
items_copy=items.copy()
print("items_view:",items_view)
print()
print("items_copy:",items_copy)
print()
print("base()'returns,\n")
print("items_view : ",items_view.base)
print("items_copy:",items_copy.base)

items: [0 1 2 3 4 5 6 7 8 9]

items_view: [0 1 2 3 4 5 6 7 8 9]

items_copy: [0 1 2 3 4 5 6 7 8 9]

base()'returns,

items_view :  [0 1 2 3 4 5 6 7 8 9]
items_copy: None


In [74]:
#vectorization
#vectorization is the process of converting an algorithm from operating on a single value at a time tp operating on a set of values(vector)at one time.

#hence ,we can use these techniques to perform operatiopns on numpy arrays without using loops.
import numpy as np
arr=np.arange(1,20,4)
arr1=np.arange(1,10,2)
print("array arr:",arr)
print("array arr1:",arr1)
arr2=(arr+arr1)
print("the sum of elements of arr and arr1 using vectorization:",arr2)

array arr: [ 1  5  9 13 17]
array arr1: [1 3 5 7 9]
the sum of elements of arr and arr1 using vectorization: [ 2  8 14 20 26]


In [75]:
import numpy as np
arr=np.arange(1,20,4)
sum=0
arr2=np.sum(arr)
print("sum of array elements using vectorization:",arr2)


sum of array elements using vectorization: 45


In [76]:
import numpy as np
arr=np.arange(1,20,4)
arr1=np.arange(1,10,2)
print("Array arr:",arr)
print("Array arr1:",arr1)
arr2=np.dot(arr,arr1)
print("product of elements of arr and arr1 using vectorization:",arr2)


Array arr: [ 1  5  9 13 17]
Array arr1: [1 3 5 7 9]
product of elements of arr and arr1 using vectorization: 305


In [77]:
#non vectorized
import numpy as np
arr=np.arange(1,20,4)
sum=0
for i in arr:
    sum=sum+i
print("sum of array elements using for loop:",sum)    

sum of array elements using for loop: 45


In [ ]:
numpy.vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,␣
↪signature=None)
Required Parameters
pyfunc: pyfunc is a required function or method. It is a parameter that can be␣
↪called or defined by the user.
Optional Parameters of np Vectorize
otypes: otypes is the output datatype. It is the specified type of data that we␣
↪want as an output. It can be a string or a list. By default, it is specified␣
↪as none.
doc: It is an optional parameter to the docstring. It can be a string. If it is␣
↪none, then the docstring will be pyfunc_doc_str.
Cache: If true and otypes is not given, it is the first function call that␣
↪determines the number of outputs. It can be bool.
excluded: The positional or keyword parameters for the functions that won't be␣
↪vectorized are represented by this parameter as a collection of strings or␣
↪integers. These parameters will be passed unmodified and directly to pyfunc.
Signature: This universal function is generalized. It is used for vectorized␣
↪matrix-vector function multiplication, e.g., (a, b), (b) -> (a). Whenever it␣
↪is specified, pyfunc will be called with (and it must return) an array␣
↪containing shapes determined by the size of the estimations for the look at␣
↪focus. Scalars are typically accepted as input and output for Pyfunc by␣
↪default.
Vectorizing a Function in NumPy
In the following examples, using def, the add function is created by passing␣
↪two parameters to perform an addition between them. After passing the add␣
↪function and setting otypes to get the desired datatype inside the np.
↪vectorize function, all work done by this function is saved in the vecfunc␣
↪variable. Now we can use vecfunc variable as a function and can pass␣
↪parameters directly into the vecfunc to get the desired result, as performed␣
↪in the def function.
    

In [80]:
import numpy as np
Sum=0
def add(a,b):
    Sum=a+b
    return Sum
Vecfunc=np.vectorize(add,otypes=[float])
print(Vecfunc(1,8))
    
    

9.0


In [82]:
import numpy as np
Sum=0
Sub=0
def add(a,b):
    Sum=a+b
    return Sum
Vecfunc=np.vectorize(add,otypes=[int])
arr1=np.arange(1,20,4)
arr2=np.arange(1,10,2)
print("array arr1:",arr1)
print("array arr2: ",arr2)
print("Sum of arr1 and arr2: ", Vecfunc(arr1,arr2))

array arr1: [ 1  5  9 13 17]
array arr2:  [1 3 5 7 9]
Sum of arr1 and arr2:  [ 2  8 14 20 26]


In [83]:
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr[8]


np.int64(8)

In [85]:
arr[1:5]

array([1, 2, 3, 4])

In [86]:
arr[0:5]


array([0, 1, 2, 3, 4])

In [ ]:
Broadcasting
NumPy arrays differ from normal Python lists because of their ability to␣
↪broadcast. With lists, you can only reassign parts of a list with new parts␣
↪of the same size and shape. That is, if you wanted to replace the first 5␣
↪elements in a list with a new value, you would have to pass in a new 5␣
↪element list. With NumPy arrays, you can broadcast a single value across a␣
↪larger set of values:

In [87]:
l=[1,2,3,4]
l[0:2]=100
l

TypeError: must assign iterable to extended slice

In [88]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [89]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [91]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [92]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
np.random.rand(5)

array([0.33084848, 0.8740573 , 0.21897902, 0.62444352, 0.50017737])

In [94]:
np.random.rand(5,5)

array([[0.63158454, 0.98610128, 0.81798249, 0.34108675, 0.6093023 ],
       [0.21854582, 0.20388951, 0.6034286 , 0.37150437, 0.70128777],
       [0.2426879 , 0.48910449, 0.50157802, 0.53654587, 0.57440929],
       [0.81587729, 0.53333093, 0.39625163, 0.67450356, 0.28144154],
       [0.71902791, 0.96039854, 0.11807671, 0.16282431, 0.76201161]])

In [ ]:
#randn-returns a sample (or samples) from the "standard normal"distribution[ = 1].unlike rand which id uniform,valus to zero are more likely tp appear.

In [95]:
np.random.randn(2)


array([ 0.15955379, -0.60057461])

In [96]:
np.random.randn(5,5)

array([[ 0.30220306,  1.25068927,  0.63078408,  0.74060517, -0.63576687],
       [ 0.28881783, -0.83414308,  0.25386901, -2.41447157,  1.40464708],
       [ 0.69521396, -0.52746453,  2.13131416, -1.09448839,  1.30874979],
       [ 0.29250355, -0.44833201,  0.12503089, -0.97464063, -0.60361025],
       [-0.29721602, -1.26459659, -1.86741642,  1.13368858,  0.22523199]])

In [97]:
np.random.randint(1,100)

74

In [100]:
a=np.random.randint(1,100,10)
a

array([49, 32, 61, 30, 18, 43, 37,  9, 16, 59], dtype=int32)

In [105]:
a.argmin()

np.int64(7)

In [106]:
a.argmax()

np.int64(2)

In [107]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [108]:
a.ravel()

array([1, 2, 3, 4])